# kafka_to_sparkstreaming_to_graph

This Spark application loads data from a Kafka queue into a DseGraph instance, by way of SparkStreaming and DseGraphFrames APIs.

== RELEVANT DOCUMENTATION

* Apache Kafka: http://kafka.apache.org/documentation/

* Apache Spark Streaming: https://spark.apache.org/docs/latest/streaming-programming-guide.html

* Kafka + Spark Streaming Integration: https://spark.apache.org/docs/latest/streaming-kafka-integration.html

* DSE GraphFrames: https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/graph/graphAnalytics/dseGraphFrameImport.html


== BUILD INSTRUCTIONS

This project leverage sbt for Scala package management and compilation. In addition, one must have DSE Spark already running on their cluster. Make sure sbt is installed on your machine (https://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html):

```
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt

```

Next, clone the `kafka_to_sparkstreaming_to_graph` project to your cluster that is running DSE Spark, and build with sbt

```
git clone git@github.com:ShaunakDas88/kafka_to_sparkstreaming_to_graph.git
cd <PATH TO kafka_to_sparkstreaming_to_graph>
sbt package
```



== ABOUT THE GRAPH DATA SET

In this Spark application, we will be dealing with a subset of the Amazon graph data set (http://jmcauley.ucsd.edu/data/amazon/links.html) to your DSE Spark cluster. The data comes in the following JSON format:


which makes the DataFrames API a natural choice to use for its storage and manipulation in Spark.

Provided in the project is a bash script for downloading
```
wget -P <DESTINATION DIRECTORY>
wget -P <DESTINATION DIRECTORY>
```


== APACHE KAFKA SETUP

This Spark application will be reading data that is streamed into appropriate queues (topics) in Kafka. The following steps will get you started with this initial setup:

*  /* From the project's root directory unpack the Kafka project that is provided:

```
cd <PATH TO kafka_to_sparkstreaming_to_graph>/resources/kafka
tar -zxvf kafka_2.11-0.11.0.1.tgz
```
You should now see a subdirectory `kafka_2.11-0.11.0.1`, which contains pre-built Kafka 2.11. 

```
automaton@ip-10-200-177-27:~/kafka_to_sparkstreaming_to_graph$ ls
build.sbt  kafka_2.11-0.11.0.1  kafka_2.11-0.11.0.1.tgz  README.md  resources  scripts  src
```
*/

* Launch the ZooKeeper server as a background process:
```
automaton@ip-10-200-177-27:~/kafka_to_sparkstreaming_to_graph$ kafka_2.11-0.11.0.1/bin/zookeeper-server-start.sh kafka_2.11-0.11.0.1/config/zookeeper.properties &
```
Note that we are specifying an already provided configuration file `kafka_2.11-0.11.0.1/config/zookeeper.properties` here. 

When listing all running Java processes, we should now see `QuorumPeerMain`
```
automaton@ip-10-200-177-27:~/kafka_to_sparkstreaming_to_graph$ jps
14417 QuorumPeerMain
14703 Jps
```



5. Launch the Kafka server as a background process:

=== LOADING THE DATA INTO KAFKA TOPICS

The main abstraction which Kafka uses for reading and storing streamed input is a topic. Our Amazon data set consists of two json files:

-
- 

Let's go ahead and make a topic for each of these files:

```


```



7. Launch the Kafka standalone application:


== RUNNING THE SPARK APPLICATION

Now that the overhead involved with setting up our Kafka topics is done, we return to the Spark application itself, for loading data into DSE Graph.
